version: '3.8'

services:
  db:
    image: postgres:17  # Указываем образ PostgreSQL версии 17
    restart: always
    environment:
      POSTGRES_DB: meat_test1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Сохраняем данные базы данных

  app:
    image: radiumr30/meattestrep:latest  # Указываем образ из вашего репозитория
    restart: always
    depends_on:
      - db
    ports:
      - "90:90"  # Порт, на котором будет доступно ваше приложение
    environment:
      DATABASE_URL: postgres://postgres:123@db:5432/meat_test1  # Параметры подключения к базе данных
      CONNECTION_STRING: "Host=localhost;Port=5432;Database=meat_test1;Username=postgres;Password=123"  # Добавленная строка подключения

volumes:
  db_data:  # Определяем том для хранения данных базы данных
