services:

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: meat_test1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres"]

    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meat_test1"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: radiumr30/meattestrep:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "90:90"
    environment:
      DATABASE_URL: postgres://postgres:123@db:5432/meat_test1
      CONNECTION_STRING: "Host=db;Port=5432;Database=meat_test1;Username=postgres;Password=123"
    networks:
      - db-network

networks:
  db-network:

volumes:
  db_data:      
