version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: meat_test1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - db-network

  app:
    image: radiumr30/meattestrep:latest
    restart: always
    depends_on:
      - db
    ports:
      - "90:90"
    environment:
      DATABASE_URL: postgres://postgres:123@db:5432/meat_test1
      CONNECTION_STRING: "Host=db;Port=5432;Database=meat_test1;Username=postgres;Password=123"
    networks:
      - db-network

networks:
  db-network:

volumes:
  db_data:
